layout_spectrum: 0.7171518
color:
  saturation: 0.8492041
  lightness: 0.9377699
  brandStrength: 0.2669429
  brandColors:
    - '#FFFFFF'
    - '#7D7E7F'
    - '#414342'
    - '#0070AD'
    - '#BDBEBD'
  rhythmicContrast: 0.7982624
typography_spectrum: 0.376568
name: Thoracolumbar fractures
